# Generated by Django 4.1.7 on 2023-10-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_task_taskmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='title',
            new_name='name',
        ),
    ]
