# Generated by Django 4.1.7 on 2023-10-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_title_taskmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
